spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tax-calculation
    username: tax-username
    password: tax-password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
security:
    oauth2:
        client:
            access-token-uri: https://dev-324543.oktapreview.com/oauth2/default/v1/token
            user-authorization-uri: https://dev-324543.oktapreview.com/oauth2/default/v1/authorize
            client-id: 0oae8qa23sL5AmNXq0h7
            scope: openid profile email
        resource:
            user-info-uri: https://dev-324543.oktapreview.com/oauth2/default/v1/userinfo
            token-info-uri: https://dev-324543.oktapreview.com/oauth2/default/v1/introspect
            prefer-token-info: false